### ISSUE TITLE
[Question❓]: this project dead????

### ISSUE THREAD

**Issue by fillwithjoy1** [davidsmorais/kuro#108]
# Question Title❓
this project dead? no github commit activity since 4 months??

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Hey @fillwithjoy1 👋

The project is not dead _per se_, it's more of an completed state as there isn't anything else I'm planning on adding, besides the usual security and package updates. And with my personal life schedule being more occupied, these are not as frequent as they once were, but Kuro 9 should still be useable and bug free 🙂


If there's a missing feature you'd like to see implemented, or a bug that's preventing you from using the app, do let me know 👍

**Comment by fillwithjoy1** [comment]
Alright all good, I'll try it out 👍
