### ISSUE TITLE
AUR build

### ISSUE THREAD

**Issue by davidsmorais** [davidsmorais/kuro#12]
Am unable to build the AUR package. Would appreciate if someone on Arch manages to build & release this

**Comment by benjezzy** [comment]
@davidsmorais Any reason why you have already closed this & haven't left it open to have someone help get into the AUR? (Might be something I'm interested in picking up in the future)

**Comment by davidsmorais** [comment]
feel free to, I just created this issue because the `pamac` build was not going through, so the title can be misleading.
It's my intention to distribute Kuro in all major repos, just wanted to polish the product a little bit more before doing so

**Comment by benjezzy** [comment]
Noted, will try to help with this one at some point when the product is a little more polished as you mentioned
