### ISSUE TITLE
General > Icon Missing

### ISSUE THREAD

**Issue by davidsmorais** [davidsmorais/kuro#3]
**Describe the bug**
The desktop icon is missing in Ubuntu 21.10

**Expected behavior**
The logo should show up in desktop & tab switcher

**Screenshots**
![image](https://user-images.githubusercontent.com/22729436/149919738-04e887c1-6434-4340-9caf-2dba2ff7d193.png)

**Comment by davidsmorais** [comment]
Re-opening this as now we get the electron default icon
![image](https://user-images.githubusercontent.com/22729436/153912971-ebc1aa76-ff5d-4534-a537-1ee8d43fbcf6.png)

**Comment by benjezzy** [comment]
Same issue on KDE Plasma 5.23 (app running via appimage)

**Comment by davidsmorais** [comment]
I hope I've fixed this in `v8.0.2`.

Please let me know if it's still breaking in KDE

**Comment by benjezzy** [comment]
@davidsmorais Latest version `8.0.2` fixes icon issue on KDE so all good. Thanks for the quick turnaround!
