### ISSUE TITLE
[Feature 🚀]: Add the app to flathub

### ISSUE THREAD

**Issue by radical4ever** [davidsmorais/kuro#36]
Hi, i would love to see this app as flatpak there are no apps related to microsoft todo. so this would be awesome if it happens

**Comment by Alexhuszagh** [comment]
The repository owner has to be the one to submit the [PR](https://github.com/flathub/flathub/wiki/App-Submission) for inclusion onto Flathub.


> 1. Fork the Flathub repository on GitHub
> 2. Clone the fork: git clone --branch=new-pr git@github.com:your_github_username/flathub.git
> 3. Create a new branch with your app’s name: git checkout -b your_app_name
> 4. Add your app’s manifest to the branch, commit it and push the commit
> 5. Open a pull request against the new-pr branch on Github
> 6. Your pull request will then be reviewed by the Flathub admins
> 
> Once your pull request has been approved, a new repository will be created for your application, containing your app’s Flatpak manifest. You will have write access for the repository. The Flathub service then uses the manifest from your repository to continuously build and distribute your application on every commit.

I can submit a PR for the manifest and similar.

**Comment by davidsmorais** [comment]
@Alexhuszagh , what about building a `.flatpak` package ? I'm assuming we need one of those to actually be in Flathub ? 😄

**Comment by Alexhuszagh** [comment]
Yep, that will be the PR, and then you can submit it to Flathub via the PR from there.

**Comment by hihain** [comment]
I would be happy to see a flatpak package, too. I want to keep the Steam Deck like Valve intended. That is why I depend on flatpak there.

**Comment by tim-gromeyer** [comment]
Any update on this?

**Comment by davidsmorais** [comment]
Hey @tim-gromeyer , sorry, I missed your message. No plans to add anything atm to Kuro as I'm not using Linux anymore, but am accepting contributions 🙏

**Comment by davidsmorais** [comment]
@DUB1401 it could be argued that the universal keyboard shortcuts are something that the webapp cannot do. Nevertheless, not my fight 🥹
