### ISSUE TITLE
[Bug 🐞]: change pacman package dependency

### ISSUE THREAD

**Issue by Reverier-Xu** [davidsmorais/kuro#37]
# change pacman package required `libappindicator-sharp` dependency to optional 🐞

hi, i'd like you to change the `libappindicator-sharp` dependency in the package to an optional dependency.

**Describe the bug**
`libappindicator-sharp` package in AUR is no longer maintained, and it is not necessary for kuro.

**Comment by Reverier-Xu** [comment]
Hi, the newest release solved the dependency problem but ... it seems not working as well.

![image](https://user-images.githubusercontent.com/41937333/174890902-c34aeb7b-ab74-49ef-b9f5-fc02c33f69d0.png)

Could you update the pacman's PKGBUILD file to this repository? maybe i can help.

**Comment by Reverier-Xu** [comment]
The electron version 19 is too high even for Arch Linux ...

![image](https://user-images.githubusercontent.com/41937333/174892287-425a53be-b8ad-4656-9e7f-5a136dfadd29.png)

it is recommended that we just publish a PKGBUILD file on aur.archlinux.org instead of build a binary package. Users could install kuro from paru/yay or other AUR package helpers. PKGBUILD is a simple pack script, we can pack the appimage as a pacman package in PKGBUILD, that solves most problems.

the appimage PKGBUILD file may looks like this:

```
# Maintainer: ???
pkgname=kuro-appimage
pkgver=8.1.1
pkgrel=1
pkgdesc="An elegant Microsoft ToDo desktop client for Linux (a fork of Ao)"
arch=("x86_64")
url="https://github.com/davidsmorais/kuro"
license=("unknown")
_pkgname="Kuro-${pkgver}.AppImage"
noextract=(${_pkgname})
options=("!strip")
provides=("kuro")
optdepends=()
source=("https://github.com/davidsmorais/kuro/releases/download/v${pkgver}/${_pkgname}")
sha512sums=("755bd884a8bd44ca383205fe9c7836a42f6e5cfce9289d0b5dbaff924404773d02110b9da4332c0556ab1924f0e5a1e1ea4a2a2f142e48e86528ebb626814038")

_installdir=/opt/appimages

prepare() {
    cd ${srcdir}
    chmod a+x ${_pkgname}
    ${srcdir}/${_pkgname} --appimage-extract >/dev/null
    sed -i "s+AppRun+env DESKTOPINTEGRATION=no ${_installdir}/Kuro.AppImage+" "squashfs-root/kuro.desktop"
    sed -i "s+Icon=kuro+Icon=kuro-appimage+" "squashfs-root/kuro.desktop"
}

package() {
    install -Dm755 ${_pkgname} "${pkgdir}/${_installdir}/Kuro.AppImage"
    install -Dm644 "squashfs-root/usr/share/icons/hicolor/1024x1024/apps/kuro.png" "${pkgdir}/usr/share/icons/hicolor/1024x1024/apps/kuro-appimage.png"
    install -Dm644 "squashfs-root/kuro.desktop" "${pkgdir}/usr/share/applications/kuro-appimage.desktop"
}
```

so that you can just publish appimage then update the PKGBUILD, all things will be done.

**Comment by davidsmorais** [comment]
@Reverier-Xu there's already an open issue for AUR package (#22). I don't have any machines running any Arch based distros, so would be great if you could help 👍 
I'm also releasing a new version with electron 18.3.4 as 19.0.5 was released yesterday 😓

**Comment by Reverier-Xu** [comment]
Hi, version 8.1.3 still not works (both pacman and appimage).

![image](https://user-images.githubusercontent.com/41937333/174949448-723275a7-04c4-4baf-a247-5d7035cef488.png)

i think the electron is not necessary to upgrade to the newest version. AppImage will pack all dependencies so that we don't need to worry about it on any linux distros.

if you want to upgrade electron, there is a lot work to do.

**Comment by davidsmorais** [comment]
I'm sorry, this is running fine in my machine, even after resetting the settings.

Can you please try and do a `rm -rf ~/.config/Kuro` ?

**Comment by Reverier-Xu** [comment]
> I'm sorry, this is running fine in my machine, even after resetting the settings.
> 
> Can you please try and do a `rm -rf ~/.config/Kuro` ?

ohh, it seems ok, thank you.
