### ISSUE TITLE
how to launch snap app? 

### ISSUE THREAD

**Issue by shmu26** [davidsmorais/kuro#45]
I installed kuro-desktop as a snap on Kubuntu 22.04
`sudo snap install kuro-desktop --edge`
then I logged out and back in
but I can't figure out how to launch it. It does not appear in list of installed apps, and does not launch by entering `kuro-desktop` in terminal. I can't locate a executable file or  .desktop file. 

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
@shmu26 should be working now in `stable` channel
