### ISSUE TITLE
[Feature 🚀]: Add Monochrome System Tray Icon

### ISSUE THREAD

**Issue by theamazing0** [davidsmorais/kuro#47]
**Is your feature request related to a problem? Please describe.**
Kuro currently uses a colored system tray icon which doesn't match with a lot of system trays.

**Describe the solution you'd like**
A monochrome black / white icon would match more.

**Comment by theamazing0** [comment]
![image](https://user-images.githubusercontent.com/66532288/178998019-aff7e161-1309-4572-a005-93308e0a5707.png)

**Comment by davidsmorais** [comment]
Hey 👋 

Great idea, I should work on a new one for the next release :ok_hand:

Thanks

**Comment by theamazing0** [comment]
Sounds cool!
