### ISSUE TITLE
[Bug 🐞]: The Suggestions Menu Background Doesnt Match With The Rest Of The App's Theme

### ISSUE THREAD

**Issue by theamazing0** [davidsmorais/kuro#48]
# Bug Title 🐞

**Describe the bug**
The Suggestions menu is not matching with rest of the theme.

**Reproduction Steps**
Click the suggestions button in My Day.

**Expected Behavior**
The Suggestions menu background is dark.

**Screenshots**
![image](https://user-images.githubusercontent.com/66532288/179843624-85085205-307f-4785-938f-0b210beec0de.png)

**Technical Info (please complete the following information)**
 - OS: EndeavorOS
 - Kuro Version: 8.1.3

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Thanks for reporting, will take a look and release a fix soon :+1:
