### ISSUE TITLE
Unfork the Repository

### ISSUE THREAD

**Issue by Alexhuszagh** [davidsmorais/kuro#50]
It is currently impossible to search forked repositories on Github, and since Kuro is now sufficiently different than AO, it's probably a good idea to unfork the repository and have it as its own repository. The process to unfork is described [here](https://stackoverflow.com/a/66470086/4131059).

**Comment by davidsmorais** [comment]
I agree, I thought of that earlier but did not find anything on the settings and just left it for later. Thanks @Alexhuszagh :+1: 

I've submitted a ticket with GH support, its up to them now :laughing:

**Comment by davidsmorais** [comment]
✅
