### ISSUE TITLE
[Bug 🐞]: Search Box Theme Color

### ISSUE THREAD

**Issue by zamanshahed** [davidsmorais/kuro#51]
# Search Box Theme Color 🐞

**Description**
while using dark theme, navigating through keyboard arrow keys (left / right) searchbox background color suddenly changes from dark to white color

**Reproduction Steps**
- click on the search box
- move the cursor left or right using keyboard arrow keys
- type anything or keep it empty does not matter

**Expected Behavior**
the search box background color should remain constantly dark or white according to the theme standard color

**Screenshots**
![image](https://user-images.githubusercontent.com/48586148/181440190-9fe3bcc0-0eec-435c-a8c7-0e21e3e4552c.png)

![image](https://user-images.githubusercontent.com/48586148/181438904-fb3616de-606e-4843-b81d-d468b960bb00.png)

**Technical Info:**
 - OS: Manjaro KDE
 - Kuro Version: 8.1.4 (installed from AUR)

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
@zamanshahed  nice find :muscle: thanks for reporting
Will take a look and fix it in the next version

**Comment by davidsmorais** [comment]
Hello @zamanshahed , this was fixed in the [new version ](https://github.com/davidsmorais/kuro/releases/tag/v8.1.5) :rocket:
