### ISSUE TITLE
[Bug 🐞]: Launch Minimized doesn't work

### ISSUE THREAD

**Issue by theamazing0** [davidsmorais/kuro#55]
# Launch Minimized doesn't work 🐞

**Describe the bug**
Despite "Launch Minimized" being turned on, the application shows its window on startup.

**Reproduction Steps**
1. Turn on Launch Minimized
2. Completely Quit & Exit Kuro
3. Run Kuro (i.e. run "kuro" in command line)

**Expected Behavior**
The window should not be shown and the system tray icon should appear.

**Technical Info (please complete the following information)**
 - OS: EndeavorOS
 - Kuro Version: 8.1.4

**Additional context**
Note: This is probably because I am using a tiling window manager (bspwm) which does not support minimized windows. 

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Hey @theamazing0  :wave: 
Thanks for reporting this :+1:  I'll try and fix this in the next version

**Comment by davidsmorais** [comment]
@theamazing0 a fix for this was just released in the [new version ](https://github.com/davidsmorais/kuro/releases/tag/v8.1.5) :rocket:
