### ISSUE TITLE
[Bug 🐞]: drag-and-drop rearrangement of tasks doesn't work correctly on macOS

### ISSUE THREAD

**Issue by rv3392** [davidsmorais/kuro#59]
# Bug Title 🐞

**Describe the bug**
On macOS, when trying to rearrange a task list by dragging-and-dropping tasks the entire window moves instead of the task. It looks like this happens because the "body" CSS selector in browser.css contains the property  `-webkit-app-region: drag;`, which from my understanding is macOS-specific.

**Reproduction Steps**
1. Build and run on macOS
2. Try to drag-and-drop a task, the entire window will move instead of the task

**Expected Behavior**
The task moves and the window stays in place.

**Screenshots**
N/A

**Technical Info (please complete the following information)**
 - OS: macOS
 - Kuro Version: 8.1.5 (build from master branch)

**Additional context**
I know that this project isn't aiming to support macOS, so I totally understand if this isn't high-priority but this was a problem that I ran into so it may be of help to others too. 

I've got a simple fix in my own fork: https://github.com/davidsmorais/kuro/compare/master...rv3392:kuro:rv3392/macos-drag-fix. The removal of `-webkit-app-region: drag;` should fix the bug itself, and then the change of `titleBarStyle: "hiddenInset"` to `titleBarStyle: "default"` adds a titlebar for macOS so that the window can still be moved. 

From my testing it looks like the code causing the problem and the subsequent fix has no impact on Linux functionality (to be clear, I've only tested on Ubuntu) where a separate titlebar is already present regardless of the `titlebarStyle` and the `-webkit-app-region: drag;` property doesn't do anything.  I'm guessing the original code was used in Ao for a cleaner UI on macOS and never had any intended function on Linux or Windows, but has gone stale over the last few years.

Let me know if this is a change you would consider and I will be happy to open a PR! Thanks :)!

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Hello @rv3392  :wave:

thanks for reporting this and taking the time to fork 🙌  I'll run some tests on my OSes too and have it in the next release if all looks good 👍

**Comment by davidsmorais** [comment]
Merged and released in [8.1.6](https://github.com/davidsmorais/kuro/releases/tag/v8.1.6)

Thanks again :pray:
