### ISSUE TITLE
[Bug 🐞]: Some deleted files are still in use

### ISSUE THREAD

**Issue by MatsG23** [davidsmorais/kuro#61]
# Bug Title 🐞

**Describe the bug**
Kuro seems to use files that has been deleted. I am not experiencing additional issues in the app.  

**Reproduction Steps**
1. Open/use Kuro
2. Download [Lynis](https://cisofy.com/downloads/lynis/)
3. Run `sudo ./lynis audit system` in the extracted directory from the download
4. You will see that test LOGG-2190 (Checking for deleted files in use) will log some messages including many from Kuro

**Expected Behavior**
Kuro should stop using files when they get deleted.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/60609373/197358511-67099f66-ad40-4579-a7db-80dbde1628cb.png)

**Technical Info (please complete the following information)**
 - OS: openSUSE Tumbleweed (Snapshot of 2022/10/22)
 - Kuro Version: 8.1.5 (AppImage)

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Hey @MatsG23 :wave: 

Thanks for reporting this. However, I am not responsible for those files.

The gvfs metadata capabilities are used by the GNOME Files file manager, and others. You can disable it.

`systemctl --user mask gvfs-metadata.service`

To revert it use

`systemctl --user unmask gvfs-metadata.service`

The other shared memory files (in `/dev/shm/`) are temporary fields created by Electron (which is what powers up Kuro) and can be attributed to Kuro cache/local storage. 

Either way Kuro is not directly responsible for these files and I don't really see much to fix here.
