### ISSUE TITLE
[Question❓]: System date & time settings not used by Kuro

### ISSUE THREAD

**Issue by SindarS** [davidsmorais/kuro#68]
# System date & time settings not used by Kuro❓
I'm not sure whether this qualifies as a bug, so I'm gonna post it as a question.
It appears that the app doesn't take into account system date & time settings when selecting "Pick a date (time)" for due date or reminders for tasks.
Specifically, my system (Debian) is set to 24-hr clock and week starting with Mon. While in the app itself I get AM/PM and mini-calendar week starting on Sun.

I couldn't find any options to change those settings within the app itself, so either the app can't properly read system settings or it defaults to US date/time format and there aren't exclusive settings to change it.
I'm running Kuro as an AppImage and otherwise haven't experienced any issues with the rest of the functionality.
The date/time issue is slightly annoying, but not the end of the world.

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Hello @SindarS  :wave: 
Thanks or reporting this.

I will investigate how the ToDo app is reading system data and check what may be failing and I'll let you know my findings.

Thanks,
David

**Comment by davidsmorais** [comment]
Thanks for the follow up. 
In my Linux machine I could not reproduce this (popOS). Will try to replicate in WSL.

Just want to ask, do you restart Kuro after changing system time ?
