### ISSUE TITLE
[Feature 🚀]: Use system electron for Arch Linux

### ISSUE THREAD

**Issue by skbeh** [davidsmorais/kuro#70]
**Is your feature request related to a problem? Please describe.**
Currently the pacman package ships an electron, which violates [Electron package guidelines](https://wiki.archlinux.org/title/Electron_package_guidelines#Using_the_system_electron) of Arch Linux and wastes space.
**Describe the solution you'd like**
- Only include `kuro.asar` and shell wrapper in the Arch package, name it as `kuro-bin` and submit the package to AUR. (It seems that it runs properly on https://archlinux.org/packages/community/x86_64/electron/)
- Make the `kuro` package in AUR be built from source.

**Comment by bilal-tasdelen** [comment]
Hi @skbeh, I am the maintainer of the kuro AUR package.

Is [kuro-electron](https://aur.archlinux.org/packages/kuro-electron) your package? I believe it does what you want.

However, there are some things I wanted to discuss.

1) Shipping the Electron with the app does not violate the [Electron package guidelines](https://wiki.archlinux.org/title/Electron_package_guidelines#Using_the_system_electron). Here are two quotes from the page:

> Arch Linux provides global [electron](https://archlinux.org/packages/?name=electron) and versioned [electron*](https://archlinux.org/packages/?q=electron) packages that **can** be used to run an electron application ...

> If the package contains a prebuilt copy of electron, copy the final distribution in its entirety to /opt/appname. 

These quotes suggest that shipping (or not) is an option, not an obligation.

2) Duplicate submissions **does** violate the guidelines [AUR submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines).

> Check the AUR if the package already exists. If it is currently maintained, changes can be submitted in a comment for the maintainer's attention. If it is unmaintained or the maintainer is unresponsive, the package can be adopted and updated as required. Do not create duplicate packages.

So, the best way to do it is to decide something and do it on the original package.

3) I agree that shipping the Electron with the Kuro wastes space,  but it is also conveinent and portable. Uusing system Electron requires additional maintanence. It needs to be updated if the Kuro decides to use a different version.

Maybe @davidsmorais can chime in on this.

**Comment by skbeh** [comment]
@bilal-tasdelen kuro-electron is not my package.
Updating electron may be the responsibility of the package maintainer, and Arch Linux repo have most of the LTS electron versions.
Usually the names of AUR packages that are not built from source have a suffix of `-bin`.

**Comment by bilal-tasdelen** [comment]
I agree with the `-bin` suffix. There were no other kuro packages around except the `kuro-appimage`, so I went with the simplest name that time, but it should have been `kuro-bin`. If someone goes there and creates a `PKGBUILD` for building kuro, I can move current version to `kuro-bin`.

**Comment by bilal-tasdelen** [comment]
@skbeh I copied my package to `kuro-bin`. Would you like me to transfer ownership of `kuro` to you?

**Comment by skbeh** [comment]
@bilal-tasdelen I may not have enough time to keep it updated. It would be better to add me to co-maintainers.

**Comment by bilal-tasdelen** [comment]
@skbeh I migrated the package to your PKGBUILD. I can add you as co-maintainer if you give me your AUR username.

One issue: Themes do not seem to work with compiled Kuro, but works fine with kuro-bin.

**Comment by benjezzy** [comment]
@bilal-tasdelen @skbeh  Themes are now broken on both `kuro` & `kuro-bin` for me, meaning I'm stuck on retina-burning 'White' theme for now. Any change we can fix or at least temporarily revert? 

Happy to help with debugging/testing.

**Comment by skbeh** [comment]
> Themes are now broken on both `kuro` & `kuro-bin` for me, meaning I'm stuck on retina-burning 'White' theme for now. Any change we can fix or at least temporarily revert?
> 
> Happy to help with debugging/testing.
Actually, Microsoft To-do has its own dark theme, which can be enabled in setting as a workaround.

**Comment by bilal-tasdelen** [comment]
@skbeh I am getting following error during `makepkg` with the updated `PKGBUILD`:

```
==> Starting build()...
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
/bin/sh: line 1: electron-builder: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by skbeh** [comment]
@bilal-tasdelen Fixed.

**Comment by bilal-tasdelen** [comment]
@skbeh The fix, worked for me. Thank you.

@benjezzy can you confirm it is fixed for you as well? I already updated the AUR package.

**Comment by davidsmorais** [comment]
Thanks for this guys :wave:  I've been away for the weekend and Arch/AUR isn't really something I can do much about :sweat_smile:

**Comment by bilal-tasdelen** [comment]
@benjezzy Thanks for testing it!

@skbeh I would suggest closing the issue, as most of your suggested solutions are implemented. Let me know if you have further requests.

**Comment by skbeh** [comment]
@bilal-tasdelen @davidsmorais Maybe we should consider moving to electron 19 now, because electron 18 is EOL since 3 months ago and it is orphan in the AUR.
In the long run, the issue with electron 20 also has to be solved.
