### ISSUE TITLE
[Question❓]: How to install Kuro from package `kuro-8.1.7.pacman`?

### ISSUE THREAD

**Issue by msoutopico** [davidsmorais/kuro#80]
# How to install Kuro from package `kuro-8.1.7.pacman`?❓

Also, the fact that this package is shipped like that, does that mean that we shouldn't do `yay -S kuro` anymore? 

Thanks a lot.

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Hello @msoutopico :wave: 
I'm not maintaing the AUR package  (see #22) so it may be a little outdated with the current version.

However, you should still be able to install kuro with `yay`

**Comment by msoutopico** [comment]
Thanks @davidsmorais 

yes, I think I could install with `yay`.

One question, though: if I install using your package `kuro-8.1.7.pacman`, is that package you maintain? 
Thanks

**Comment by davidsmorais** [comment]
@msoutopico, everytime I build a new version,  I upload it to the [releases](https://github.com/davidsmorais/kuro/releases) page and to [Snap](https://snapcraft.io/kuro-desktop). However, [another user](https://github.com/davidsmorais/kuro/issues/22#issuecomment-1359180122) has been uploading the updates into AUR.

If you download the `pacman` build from the releases page, then yes, I've uploaded it. If you try to download from AUR, it was uploaded by a community user, and maybe a little outdated, but it's the same package that's on the releases page.

**Comment by msoutopico** [comment]
Thank you, @davidsmorais. That is fine, but I think my question wasn't clear. I don't need to install from AUR, I'm fine with installing the `pacman` build that you release directly, and I prefer that.

I would just need to know how one installs the `pacman` build, could you point me to the instructions or write them here? I downloaded the `kuro-8.1.7.pacman` package but I don't know what to do with it.

Sorry if it's a silly question. Thank you so much.

**Comment by davidsmorais** [comment]
@msoutopico I believe the install command would be `pacman -S kuro-8.1.7.pacman` in this case.

**Comment by msoutopico** [comment]
Thanks, David.  That's the info I needed to have (and I couldn't find). Cheers!
