### ISSUE TITLE
[Bug 🐞]: Web Links open in Wayland WebView

### ISSUE THREAD

**Issue by MatsG23** [davidsmorais/kuro#81]
**Describe the bug**
Since Kuro 8.1.7, web links are opened in something like a WebView (seperate window) with a default Wayland icon.

**Reproduction Steps**
1.  Create a To Do element with a web links in the task, subtask or description
2. Click on the web link

**Expected Behavior**
The web link should be opened in the external (default) browser. 

**Screenshots**
![image](https://user-images.githubusercontent.com/60609373/215266039-3e7e93af-bd1b-4882-901d-801d187c2b2a.png)

**Technical Info**
 - OS: openSUSE Tumbleweed 20230126
 - Desktop environment: KDE Plasma 5.26.5 (Wayland)
 - Kuro Version: 8.1.7

**Additional context**
The default behaviour for opening web links may have changed in the Electon update.

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Wow, big one, thanks for reporting it @MatsG23 I'll take a look with top priority. Expect to have a fix ready by Monday/Tuesday tops.
