### ISSUE TITLE
Unable to change theme color

### ISSUE THREAD

**Issue by AndyHCode** [davidsmorais/kuro#82]
**Describe the bug**
unable to change the theme and have been stuck on the white theme.

**Reproduction Steps**
view->toggle theme->[any theme]

**Expected Behavior**
being able to switch themes

![image](https://user-images.githubusercontent.com/82745396/215360834-cfd07b54-7d59-464c-b31d-a8cb74cf8e29.png)

**Technical Info**
+ OS: EndeavourOS Linux x86_64
+ Desktop environment: i3
+ Kuro Version: 8.1.7-1

Note: downloaded through the arch aur. tested Kuro, Kuro-bin, Kuro-appimage.

**Comment by davidsmorais** [comment]
Hey :wave: 
Thanks for reporting, a new version 8.1.8 should address these issues
