### ISSUE TITLE
[Bug 🐞]: Click on a tag opens external browser window

### ISSUE THREAD

**Issue by vitovt** [davidsmorais/kuro#86]
# Click on a tag opens external browser window 🐞

**Describe the bug**
Tag is a part of task name starting with # 
f.e. #home #projectname #important #car , etc ...

If I click on any tag inside any task name, filter applies and I see tasks tagged by this tag only. (it is OK)
BUT also opens this link in external browser: **https://to-do.live.com/search/%23TAGNAME**

where TAGNAME is name of my tag after #

**Reproduction Steps**
Create one or more tasks with #tagname in it's title
Click on #tagname

**Expected Behavior**
Filtering will work as works now, but external window shouldn't open

**Technical Info (please complete the following information)**
 - OS: Ubuntu 22.04
 - Kuro Version: 8.1.8

**Additional context**
Maybe this issue is related: https://github.com/davidsmorais/kuro/issues/81

**Comment by davidsmorais** [comment]
Thanks for the report :+1: 
Will investigate and try to release a fix soon

**Comment by davidsmorais** [comment]
Thanks for the report :+1: 
Will investigate and try to release a fix soon
