### ISSUE TITLE
[Bug 🐞]: Tray Icon bugged on Wayland

### ISSUE THREAD

**Issue by davidsmorais** [davidsmorais/kuro#87]
# Tray Icon missing on Wayland

**Describe the bug**
The tray icon does not show on Wayland desktops. This is a known [electron-issue](https://github.com/electron/electron/issues/34801)

**Reproduction Steps**
Close electron to the tray in Wayland desktops
![image](https://user-images.githubusercontent.com/22729436/218544425-ca44916c-0775-4c49-a74f-0de6a251a5ba.png)
App Icon shows

**Expected Behavior**
White tray icon should apply

**Technical Info (please complete the following information)**
 - OS: PopOS 21.04
 - Kuro Version: 0.1.7+

**Additional context**
This depends on electron being fixed and updated in Kuro

**Comment by toprak** [comment]
@davidsmorais I have another tray bug icon, I clicked hide tray icon and restarted it normally gone when I click again hide tray icon the tick gone but even though I restarted the kuro icon does not come back

**Comment by davidsmorais** [comment]
@toprak I will check that behavior out next week, thanks for reporting 👍

**Comment by davidsmorais** [comment]
@toprak I've tried to reproduce your issue but was not able, maybe I didn't understand correctly, could you please open a new issue with the detailed reproduction steps ? :pray: 
Here's what I've tried

- Kuro has tray icon **shown** > When I close the main window, Kuro minimizes to the system tray :heavy_check_mark: 
- I click on `Hide Tray Icon` and Kuro prompts for a restart :heavy_check_mark: 
- Kuro restarts with tray icon **hidden** > When I close the main window, Kuro kills the process :heavy_check_mark: 


Did I miss something ?
