### ISSUE TITLE
[Question❓]: How to open kuro main menu?

### ISSUE THREAD

**Issue by KOT040188** [davidsmorais/kuro#92]
I have hidden kuro's main menu, how do I open it now?

**Comment by davidsmorais** [comment]
I don't know exactly what menu you're referring to. The context menu from the tray indicator ? The main window menu ? If the latter, please try pressing "Alt" with the Kuro window focused.

Would also be helpful to learn what's your OS and a screenshot of your window or where you expected the menu to be.

**Comment by KOT040188** [comment]
Opensuse. The main window menu. I hid it using the corresponding option in this menu.  I don't think it's worth showing what is not visible now.

**Comment by davidsmorais** [comment]
Can you show the titlebar where the menu was supposed to be 🙏 ? 
Also, which binary are you running ? `AppImage`, `snap`, other ?

**Comment by KOT040188** [comment]
I am using appimage.  I'm away from the computer now.  I forgot to add above that alt doesn't help to show the menu.

**Comment by davidsmorais** [comment]
You may want to try `Ctrl` + `O` (or `Ctrl` + `B` if your config is previous to Kuro 9)
