### ISSUE TITLE
[Question❓]: Some keys are not working.. How can I get focus to tasks?

### ISSUE THREAD

**Issue by Cruising0904** [davidsmorais/kuro#98]
# Question Title❓

Some keys are not working.. How can I get focus to tasks?

---
cc:
@davidsmorais

not working 
Ctrl + q
Ctrl + j 
Ctrl + shift + n
ctrl + alt + c

How can I custom key bindings and is there a way to focus with keys

env 
![image](https://user-images.githubusercontent.com/29267295/233813542-c0ccd460-8909-4c4e-a17d-8523242315a0.png)

**Comment by davidsmorais** [comment]
Hey @Cruising0904 👋

Can you show your `config.json` ? 🙏

**Comment by Cruising0904** [comment]
I didn't wright any config yet.. 
I was going to config keymaps after though
