### ISSUE TITLE
Trouble signing in to Microsoft account from Linux?

### ISSUE THREAD

**Issue by shmu26** [davidsmorais/kuro#99]
On all my linux distros, I have trouble signing into Microsoft Todo. Not just in Kuro but also from the browser. 
Has anyone else experienced this difficulty? Any solutions?

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Maybe you want to share a few more details on exactly what happens when you have trouble signing into ToDo.

But since this also happens in the browser, I'm going to assume this has nothing to do with Kuro...

**Comment by shmu26** [comment]
On Kuro I get a white, blank screen. But yes, the problem is bigger than just Kuro.

**Comment by davidsmorais** [comment]
> On Kuro I get a white, blank screen. But yes, the problem is bigger than just Kuro. 

Can you login to your outlook account on a browser ? Does it fail other Microsoft services or only ToDo ?
Have you tried incognito mode ?

I have no idea what your issue may be, but I would start with checking those

**Comment by zjuyk** [comment]
@shmu26 I had the same issue before and finally realized that it was just a network issue. 

Please press `F12` to check the status of each network request, `Ctrl+R` to reload.
